### ISSUE TITLE
storage implementation can't use non-negative only variables

### ISSUE THREAD

**Issue by hunteke** [hunteke/temoa#12]
Temoa currently models storage via this equation:

```
0 == sum(
    M.Efficiency[i, t, v, o]
  * M.V_FlowIn[p, s, S_d, i, t, v, o]
  - M.V_FlowOut[p, s, S_d, i, t, v, o]

  for S_d in M.time_of_day
)
```

The modeling assumption (and explained in the function's docstring) is that Temoa can let FlowIn or FlowOut be negative within a day, so long as summed over the whole season, that storage mechanism's net energy transfer is 0.

However, the VlowIn and FlowOut variables are defined in the domain "NonNegativeReals".  In other words neither can go below zero!  This means that any storage will effectively not be used, and will be treated as a normal energy producer.

The first suggestion at fixing this is to change the NonNegativeReals assumption for all storage technologies.

**Comment by jdecarolis** [comment]
> However, the VlowIn and FlowOut variables are defined in the domain
> "NonNegativeReals". In other words neither can go below zero! This means
> that any storage will effectively not be used, and will be treated as a
> normal energy producer.
> 
> The first suggestion at fixing this is to change the NonNegativeReals
> assumption for all storage technologies.

I'm not sure what the problem is with the formulation. FlowIn and FlowOut
should both be NonNegativeReals, and that is what the Temoa storage
equation expects. The minus sign in the equation is explicit, and works
when both flow types are positive. Am I missing something?

**Comment by hunteke** [comment]
Bah, finally getting back to this.  No, you are correct.  I'm not sure what I was thinking when I wrote this ticket.  Sigh.  It takes all kinds.  Thanks.
