### ISSUE TITLE
Updating Vintages

### ISSUE THREAD

**Issue by charlieeo** [hunteke/temoa#24]
After entering additional model vintages and pushing update the following message pops up. 

405 (method not allowed) - Your browser requested an action or resource through an incorrect mechanism. This most likely indicates inconsitent logic in the Temoa web interface: if you can consistently recreate this message, please consider providing the Temoa Project with a bug report. Note that unless there is an exact mechanism to recreate the issue, we may not be able to fix it.

**Comment by hunteke** [comment]
Bah, right on.  Silly "thinko" on my part.  I required that the code accessed by the "update" only take a POST request from the browser, but then outsourced to another function that required a GET request.  In essence, `1 != 2`.  I'll fix this shortly.
